service: order-testers

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    NODE_CONFIG_DIR: ./node_modules/@mazeapp/maze-api-core/config
    NODE_ENV: ${opt:stage, 'development'}

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

functions:
  helloWorld:
    handler: src/handlers.helloWorld

stepFunctions:
  stateMachines:
    orderTesters:
      name: ${self:service}-${opt:stage}-stepFunctions-orderTesters
      definition:
        StartAt: createHIT
        States:
          createHIT:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-createHIT
            ResultPath: $.data
            Next: createPanelOrder
          createPanelOrder:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-createPanelOrder
            ResultPath: $.data
            Next: debitCredits
          debitCredits:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-debitCredits
            End: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-step-functions
  - serverless-pseudo-parameters
