service: hello-service

provider:
  name: aws
  tracing: true
  runtime: nodejs12.x
  environment:
    NODE_CONFIG_DIR: ./node_modules/@mazeapp/maze-api-core/config
    NODE_ENV: ${opt:stage, 'development'}
    AWS_XRAY_CONTEXT_MISSING: 'LOG_ERROR'
  iamRoleStatements:
    - Effect: 'Allow' # xray permissions (required)
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 3
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

functions:
  helloWorld:
    handler: src/handlers.helloWorld


plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-prune-plugin
  - serverless-plugin-tracing
